# Generated by Django 4.0 on 2022-08-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('pinned_tweet_id', models.BigIntegerField(blank=True, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=64)),
                ('verified', models.BooleanField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='theapp.category')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='theapp.group')),
                ('universe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='universes', to='theapp.universe')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=280)),
                ('like_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('social_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='theapp.user')),
            ],
        ),
    ]
