# Generated by Django 4.0 on 2022-08-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_alter_user_category_alter_user_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
